# AUTOMATICALLY GENERATED by clan
{ self, ... }: {
  imports =
    let
      relPaths = builtins.fromJSON (builtins.readFile ./imports.json);
      paths = map (path: ./. + path) relPaths;
    in
    paths ++ [
      self.inputs.clan-core.clanModules.core
      {
        clan.netowkring.zerotier.networkId = builtins.readFile ./.zerotier.id;
      }
    ];
}
