name: update-flake-lock
on:
  workflow_dispatch: # allows manual triggering
  pull_request:
  schedule:
    - cron: '0/2 * * * *' # runs weekly on Sunday at 00:00

jobs:
  lockfile:
    runs-on: nix
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Update flake.lock
        uses: DeterminateSystems/update-flake-lock@v19
        with:
          pr-title: "Update flake.lock" # Title of PR to be created
          pr-labels: |                  # Labels to be set on the PR
            dependencies
            automated
