site_name: Clan Documentation
site_url: https://docs.clan.lol
repo_url: https://git.clan.lol/clan/clan-core/
repo_name: clan-core
edit_uri: _edit/main/docs/docs/

validation:
  omitted_files: warn
  absolute_links: warn
  unrecognized_links: warn

markdown_extensions:
  - admonition
  - attr_list
  - footnotes
  - md_in_html
  - def_list
  - meta
  - plantuml_markdown
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.details
  - pymdownx.highlight:
      use_pygments: true
      anchor_linenums: true
  - pymdownx.keys
  - toc:
      title: On this page

exclude_docs: |
  .*
  !templates/
  /drafts/

nav:
  - Getting started:
      - index.md
      - Installer: getting-started/installer.md
      - Configure: getting-started/configure.md
      - Secrets & Facts: getting-started/secrets.md
      - Deploy Machine: getting-started/deploy.md
      - Disk Encryption: getting-started/disk-encryption.md
      - Mesh VPN: getting-started/mesh-vpn.md
      - Backup & Restore: getting-started/backups.md
      - Flake-parts: getting-started/flake-parts.md
  - Guides:
      - guides/index.md
      - Inventory: guides/inventory.md
  - Reference:
      - reference/index.md
      - Clan Modules:
          - reference/clanModules/borgbackup-static.md
          - reference/clanModules/borgbackup.md
          - reference/clanModules/deltachat.md
          - reference/clanModules/dyndns.md
          - reference/clanModules/nginx.md
          - reference/clanModules/vaultwarden.md
          - reference/clanModules/ergochat.md
          - reference/clanModules/garage.md
          - reference/clanModules/golem-provider.md
          - reference/clanModules/index.md
          - reference/clanModules/iwd.md
          - reference/clanModules/localbackup.md
          - reference/clanModules/localsend.md
          - reference/clanModules/matrix-synapse.md
          - reference/clanModules/moonlight.md
          - reference/clanModules/mumble.md
          - reference/clanModules/packages.md
          - reference/clanModules/postgresql.md
          - reference/clanModules/root-password.md
          - reference/clanModules/single-disk.md
          - reference/clanModules/sshd.md
          - reference/clanModules/static-hosts.md
          - reference/clanModules/sunshine.md
          - reference/clanModules/syncthing-static-peers.md
          - reference/clanModules/syncthing.md
          - reference/clanModules/thelounge.md
          - reference/clanModules/trusted-nix-caches.md
          - reference/clanModules/user-password.md
          - reference/clanModules/xfce.md
          - reference/clanModules/zerotier-static-peers.md
          - reference/clanModules/zt-tcp-relay.md
      - CLI:
          - reference/cli/index.md
          - reference/cli/backups.md
          - reference/cli/facts.md
          - reference/cli/flakes.md
          - reference/cli/flash.md
          - reference/cli/history.md
          - reference/cli/machines.md
          - reference/cli/secrets.md
          - reference/cli/show.md
          - reference/cli/ssh.md
          - reference/cli/state.md
          - reference/cli/vms.md
      - Clan Core:
          - reference/clan-core/index.md
          - reference/clan-core/backups.md
          - reference/clan-core/facts.md
          - reference/clan-core/sops.md
          - reference/clan-core/state.md
          - reference/clan-core/deployment.md
          - reference/clan-core/networking.md
      - Nix API:
          - reference/nix-api/index.md
          - buildClan: reference/nix-api/buildclan.md
          - Inventory: reference/nix-api/inventory.md
  - Contributing: contributing/contributing.md
  - Blog:
      - blog/index.md

docs_dir: site
site_dir: out

theme:
  font: false
  logo: https://clan.lol/static/logo/clan-white.png
  favicon: https://clan.lol/static/dark-favicon/128x128.png
  name: material
  features:
    - navigation.instant
    - navigation.tabs
    - content.code.annotate
    - content.code.copy
    - content.tabs.link
  icon:
    repo: fontawesome/brands/git-alt
  custom_dir: overrides

  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      accent: deep purple
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      primary: teal
      accent: deep purple
      scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

extra_css:
  - static/extra.css

extra:
  social:
    - icon: fontawesome/regular/comment
      link: https://matrix.to/#/#clan:lassul.us
    - icon: fontawesome/brands/gitlab
      link: https://git.clan.lol/clan/clan-core
    - icon: fontawesome/brands/github
      link: https://github.com/clan-lol/clan-core
    - icon: fontawesome/solid/rss
      link: /feed_rss_created.xml

plugins:
  - search
  - blog
  - macros
  - rss:
      match_path: blog/posts/.*
      use_git: false
      date_from_meta:
        as_creation: "date"
        as_update: "date"
        datetime_format: "%Y-%m-%d %H:%M"
        default_timezone: Europe/Paris
        default_time: "17:18"
      categories:
        - categories
        - tags
