[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"


[project]
name = "clan-vm-manager"
dynamic = ["version"]
scripts = { clan-vm-manager = "clan_vm_manager:main" }

[tool.setuptools.packages.find]
exclude = ["result"]

[tool.setuptools.package-data]
clan_vm_manager = ["**/assets/*"]

[tool.pytest.ini_options]
testpaths = "tests"
faulthandler_timeout = 60
log_level = "DEBUG"
log_format = "%(levelname)s: %(message)s\n       %(pathname)s:%(lineno)d::%(funcName)s"
addopts = "--cov . --cov-report term --cov-report html:.reports/html --no-cov-on-fail --durations 5 --color=yes -vv --new-first" # Add --pdb for debugging
norecursedirs = "tests/helpers"
markers = ["impure"]

[tool.mypy]
python_version = "3.11"
warn_redundant_casts = true
disallow_untyped_calls = true
disallow_untyped_defs = true
no_implicit_optional = true
exclude = '^tests/helpers/libvncclient.py$'

[[tool.mypy.overrides]]
module = "clan_cli.*"
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = "libvncclient.*"
ignore_missing_imports = true


[tool.ruff]
target-version = "py311"
line-length = 88
lint.select = [ "E", "F", "I", "U", "N", "RUF", "ANN", "A" ]
lint.ignore = ["E501", "E402", "N802", "ANN101", "ANN401", "A003"]
