[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"



[project]
name = "clan-vm-manager"
dynamic = ["version"]
scripts = { clan-vm-manager = "clan_vm_manager:main" }

[tool.setuptools.packages.find]
exclude = ["result"]

[tool.setuptools.package-data]
clan_vm_manager = ["**/assets/*"]

[tool.mypy]
python_version = "3.11"
warn_redundant_casts = true
disallow_untyped_calls = true
disallow_untyped_defs = true
no_implicit_optional = true

[tool.ruff]
target-version = "py311"
line-length = 88
lint.select = [ "E", "F", "I", "U", "N", "RUF", "ANN", "A" ]
lint.ignore = ["E501", "E402", "N802", "ANN101", "ANN401", "A003"]
